### ISSUE TITLE
The theme should not give content that is wider than the image

### ISSUE THREAD

**Issue by rraub** [gios-asu/SoS-Wordpress-Theme#21]
Check out the [google mobile friendly test](https://www.google.com/webmasters/tools/mobile-friendly/)

**Comment by rraub** [comment]
Check out the google mobile friendly test

**Comment by rraub** [comment]
Ended up the robots.txt was blocking css assets so it rendered incorrectly.

**Comment by rraub** [comment]
FYI @idmontie

**Comment by idmontie** [comment]
KNEW IT!
